name: vapabi
version: master
summary: encodes smart contracts function calls and decodes their output
description: |
  An Vapory smart contract is bytecode, EVM, on the Vapory blockchain.
  Among the VVM, there could be several functions in a contract. An ABI is
  necessary so that you can specify which function in the contract to invoke,
  as well as get a guarantee that the function will return data in the format
  you are expecting.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict

apps:
  vapabi:
    command: vapabi
    plugs: [home]

parts:
  vapabi:
    source: .
    source-subdir: cli
    plugin: rust
